export enum StockType {
    IN_STOCK = 'IN STOCK',
    PARTIALLY_AVAILABLE = 'PARTIALLY AVAILABLE',
    IN_PREORDER = 'IN PREORDER',
    RESTOCK_EXPECTED = 'RESTOCK EXPECTED',
    RETAILED = 'RETAILED',
    OUT_OF_STOCK = "OUT_OF_STOCK",
}